package com.jgsu.imessage.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table CONTACT.
 */
public class Contact {

    private String account;
    private String nick;
    private Integer avator;
    private String spell;
    private Long id;

    public Contact() {
    }

    public Contact(Long id) {
        this.id = id;
    }

    public Contact(String account, String nick, Integer avator, String spell, Long id) {
        this.account = account;
        this.nick = nick;
        this.avator = avator;
        this.spell = spell;
        this.id = id;
    }

    public String getAccount() {
        return account;
    }

    public void setAccount(String account) {
        this.account = account;
    }

    public String getNick() {
        return nick;
    }

    public void setNick(String nick) {
        this.nick = nick;
    }

    public Integer getAvator() {
        return avator;
    }

    public void setAvator(Integer avator) {
        this.avator = avator;
    }

    public String getSpell() {
        return spell;
    }

    public void setSpell(String spell) {
        this.spell = spell;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

}
